### ISSUE TITLE
Remember panel sizes in local-storage.

### ISSUE THREAD

**Issue by philcockfield** [storybook-eol/storybook-ui#62]
Cross referencing this issue over to the actual repo: https://github.com/storybooks/react-storybook/issues/466

-----

Would be great if the action-logger panel, and the index panel, didn't not lose their size between page loads.

![image](https://cloud.githubusercontent.com/assets/185555/20609002/2d9ad814-b2ec-11e6-893e-7b906af66520.png)

**Comment by willowcheng** [comment]
Would love to see that width can be remembered if down panel is configured to be displayed on right.

**Comment by ndelangen** [comment]
PR is very much welcome @willowcheng ❤️

**Comment by benediktvaldez** [comment]
Does this previous change not solve this issue as well @willowcheng ? Haven't tried it out though, but if not, it could at least be an idea of how to tackle it.

https://github.com/storybooks/storybook-ui/pull/74/files#diff-45accb91d04d726de15be9e2a89530ebR172

**Comment by willowcheng** [comment]
Hi @benediktvaldez, it actually works and I thought it's already available to newest storybook release. 

Created #80 to remember both width and height in case of use cases that need to switch panel position. I found that by dragging splitter and then changing down panel position, the `height` would be instantly carried to `width` without applying rendering, no idea how to solve it.

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!
