### ISSUE TITLE
Improve Story Index

### ISSUE THREAD

**Issue by philcockfield** [storybook-eol/storybook-ui#63]
I'd like to write a better index panel that can better handle larger projects and libraries, and provide more sophisticated organisation options for stories.

![image](https://cloud.githubusercontent.com/assets/185555/20609035/89ba9008-b2ec-11e6-9fc1-11d87c3ad986.png)

Is there a pluggable way to do this.  Can I write this as an external module, and have it dropped in using a known set of properties that get passed to it.  (I'd like to write it in Typescript).  Or do I have to hack it out within this repo?

Please let me know options - and how pluggable UI want to make the Storybook?  Thanks.

**Comment by arunoda** [comment]
Currently, it's not pluggable and with current state, I think it's hard to do so. Since it's a core component of storybook.

Anyway, I think there's a huge opportunity for an improvement. So, I'd like to see it lands to the core.
If that's kind a impossible, let's try to make it pluggable.

**Comment by philcockfield** [comment]
OK, I think I'll draw up some designs.  I have some ideas that allows for clean, nested organization of stories that would not change the `storiesOf` data structure at all.

**Comment by arunoda** [comment]
Awesome.

**Comment by benediktvaldez** [comment]
@philcockfield did you ever get any further with those designs? really excited to see something like this happen

**Comment by philcockfield** [comment]
Hey @benediktvaldez - I haven't pushed that forward yet.  What's the future of Storybook looking like (before I invest time)?

**Comment by ndelangen** [comment]
Hey Phil,
I think storybooks future looks pretty bright, recently quite a few people stepped forward to maintain the packages, and we're making a lot of progress getting ready for the 3.0.0 release.
It will contain an upgrade to webpack 2, which will help a lot of people out.

We'd love to hear your ideas for designs, make people even happier?

**Comment by philcockfield** [comment]
OK, cool - that's encouraging.  I'll look to put something together ASAP.

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!
