### ISSUE TITLE
Can't perform shortcut when input is focused

### ISSUE THREAD

**Issue by willowcheng** [storybook-eol/storybook-ui#81]
In #60, it was discussed to fix the bug as `⌘ ⇧ →` and `⌘ ⇧ ←` would trigger shortcut if `<input>` is focused. Along with the fix, it would also remove part of functionality of shortcut. Check this [repo](https://github.com/willowcheng/storybook-ui/tree/demo-shortcus-for-input) for minimal reproducing with auto focused `<input>`.

The first time I got into trouble was using shortcut to toggle search box, I couldn't dismiss it until it's unfocused.

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!
