### ISSUE TITLE
Toggle Full Screen Mode shortcut for Mac doesn't work

### ISSUE THREAD

**Issue by willowcheng** [storybook-eol/storybook-ui#82]
`⌘ ⇧ F` would cause error shown in below and doesn't work, while `⌃ ⇧ F` works properly. Can be reproduced by HEAD commit of current master branch.

<img width="1276" alt="screen shot 2017-04-12 at 10 42 23 pm" src="https://cloud.githubusercontent.com/assets/6239076/24988140/05eeae32-1fd2-11e7-80bf-3cc3a7e69715.png">

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!
